package com.eclipse.AdamBrowning;
import java.util.Scanner;
//Author: Adam Browning
//Date: 16 Oct. 2017.
//Purpose: Word game where the computer draws a random number, and the user inputs a number.

public class RockPaperScissorsLizardSpock2AB {
	public static void main(String[] args) {
		
		
		//Random number generator where the computer pick a number.
	
		int comp = (int) (Math.random() * 4);
		
		
	
		//Into telling the user how to play the game. and giving them the definitions for each number.
		System.out.println("Welcome to Rock, Paper, Scissor, Lizard, Spock(TM). You will be prompted to input a number.");
		System.out.println("The definitions are: 0 = Rock, 1 = paper, 2 = scissors, 3 = lizard and 4 = Spock.  ");
		
		//user enters the number

		System.out.print("Please enter your number: ");
		Scanner input = new Scanner(System.in);
		int user = input.nextInt();
		
		
		//print out with final results.
		System.out.println("Here are the results \n" );
		results(user, comp);
	
	}
		
	//Results method where most of the work happends.
	public static void results(int user, int comp) {
	
		//name associated to the users number.
		if (user == 0) {
				System.out.print("You picked rock,");
		}
			else if (user == 1) {
				System.out.print("You picked paper,");
			}
			else if (user == 2) {
				System.out.print("you picked scissor,");
				
			}	
			else if (user == 3) {
				System.out.print("You picked lizard,");
			}
			else if (user == 4) {
				System.out.print("You picked spock,");
			}
	
		//Number randomly generated by the computer is given a name.
		if (comp == 0) {
			System.out.print(" Sheldon picked rock,");
			}
		
		else if (comp == 1) {
			System.out.print(" T-800 picked paper,");
		}
		
		else if (comp == 2) {
			System.out.print(" the toster picked scissors,");
			
		}	
		
		else if (comp == 3) {
			System.out.print(" Cylon picked lizard,");
		}
		
		else if (comp == 4) {
			System.out.print(" skynet picked spock,");
		}
		

		//Final results. Names are not input into user and comp area.
		if (user == 0 && comp == 3) {
			System.out.print(" you win.");
		}
		
		else if (user == 1 && comp == 3) {
			System.out.print(" Toaster wins" );
		}
		
		else if (user == 2 && comp == 1) {
			System.out.print(" you win");
		}
		
		else if (user == 3 && comp == 4) {
			System.out.print(" Cylon wins");
		}
		
		else if (user == 4 && comp == 1) {
			System.out.print(" you win");
		}
		
		else if (user == 0 && comp == 1) {
			System.out.print(" Skynet wins");
		}
		
		else if (user == 1 && comp == 0) {
			System.out.print(" you win");
		}
		
		else if (user == 2 && comp == 4) {
			System.out.print(" Wally wins");
		}
		
		else if (user == 3 && comp == 2)  {
			System.out.print(" T-800 wins");
		}
		
		else if (user == 4 && comp == 0) {
			System.out.print(" you win");
		}
		
		else if (comp == 0 && user ==3) {
			System.out.print(" you win.");
		}
		else if (comp == 1 && user == 3) {
			System.out.print(" you win." );
		}
		else if (comp == 2 && user == 1) {
			System.out.print(" Skynet wins.");
		}
		else if (comp == 3 && user == 4) {
			System.out.print(" computer win");
		}
		else if (comp == 4 && user == 1) {
			System.out.print(" computer win");
		}
		else if (comp == 0 && user == 1) {
			System.out.print(" you win");
		}
		else if (comp == 1 && user == 0) {
			System.out.print("C3-PO win");
		}
		else if (comp == 2 && user == 4) {
			System.out.print(" you win");
		}
		else if (comp == 3 && user == 2)  {
			System.out.print(" you win");
		}
		else if (comp == 4 && user == 0) {
			System.out.print(" Cylon Toaster wins some bread.");
		}
		if (user == 0 && comp == 0) {
			System.out.print(" tie.");
		}
		else if (user == 1 && comp == 1) {
			System.out.print(" tie" );
		}
		else if (user == 2 && comp == 2) {
			System.out.print(" tie");
		}
		else if (user == 3 && comp == 3) {
			System.out.print(" tie");
		}
		else if (user == 4 && comp == 4) {
			System.out.print(" tie");
		}
	
		
	
	
	}
		
		
}


	